# Dataset paths
raw_data_dir: "/home/dilith_s_b_s/UoP/Sem_4/CO5430/CVProject/Datasets/akhatova/pcb-defects/versions/1/PCB_DATASET"
processed_data_dir: "/home/dilith_s_b_s/UoP/Sem_4/CO5430/CVProject/data/processed"

# Tiling parameters
tile_size: 640
overlap: 0.15

# Training parameters
batch_size: 16
epochs: 50
model_name: "yolo11n.pt"
