# Dataset paths
classical_data_dir: "/new-home/e23/e23336/UoP/Sem_4/CO5430/CVProject/datasets/PCB_DATASET"
dl_data_dir: "/new-home/e23/e23336/UoP/Sem_4/CO5430/CVProject/datasets/PKU-Market-PCB(Data enhanced version)"
processed_data_dir: "/new-home/e23/e23336/UoP/Sem_4/CO5430/CVProject/data/processed"

# Tiling parameters
tile_size: 640
overlap: 0.15

# Training parameters
batch_size: 32
epochs: 100
model_name: "yolo11n.pt"
